### ISSUE TITLE
LoadError of rubygems/builder using JRuby 1.7.5

### ISSUE THREAD

**Issue by daveinman** [TwP/bones#42]
Using JRuby version 1.7.5 I get:

```
% jirb
irb(main):001:0> require 'bones'
LoadError: no such file to load -- rubygems/builder
        from org/jruby/RubyKernel.java:1082:in `require'
        from /export/pack/jruby-1.7.5-di/x86_64-Linux-2.6/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53:in `require'
        from /export/pack/jruby-1.7.5-di/x86_64-Linux-2.6/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:51:in `require'
        from /home/davei/.gem/jruby/1.9/gems/bones-3.8.1/lib//bones/gem_package_task.rb:8:in `(root)'
        from org/jruby/RubyKernel.java:1082:in `require'
        from /export/pack/jruby-1.7.5-di/x86_64-Linux-2.6/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53:in `require'
        from /export/pack/jruby-1.7.5-di/x86_64-Linux-2.6/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:51:in `require'
        from /home/davei/.gem/jruby/1.9/gems/bones-3.8.1/lib/bones.rb:1:in `(root)'
        from /home/davei/.gem/jruby/1.9/gems/bones-3.8.1/lib/bones.rb:91:in `(root)'
        from /home/davei/.gem/jruby/1.9/gems/bones-3.8.1/lib/bones.rb:58:in `libpath'
        from org/jruby/RubyKernel.java:1082:in `require'
        from /home/davei/.gem/jruby/1.9/gems/bones-3.8.1/lib/bones.rb:87:in `(root)'
        from /export/pack/jruby-1.7.5-di/x86_64-Linux-2.6/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1:in `(root)'
        from org/jruby/RubyKernel.java:1121:in `eval'
        from /export/pack/jruby-1.7.5-di/x86_64-Linux-2.6/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:133:in `require'
        from (irb):1:in `evaluate'
        from org/jruby/RubyKernel.java:1517:in `loop'
        from org/jruby/RubyKernel.java:1282:in `catch'
        from org/jruby/RubyKernel.java:1282:in `catch'
        from /usr/pack/jruby-1.7.5-di/x86_64-Linux-2.6/bin/jirb:13:in `(root)'irb
```

A fix for the problem is to modify gem_package_task.rb this way:

```
...
# dmi code
#if RUBY_VERSION >= "2"
#  require 'rubygems/package'
#else
#  require 'rubygems/builder'
#end
begin
    # for ruby 2.0 or jruby 1.7.5 
    require 'rubygems/package'
rescue LoadError
    require 'rubygems/builder'
end
# end dmi code
...
```

I'll yield to others with greater knowledge of compatibility issues for any
other form of fix, but the above seems to work for me.

**Comment by kares** [comment]
**still** the case with latest 1.7 (at the time being **1.7.18**) ... as the releases come with "older" RubyGems
